name: ${project.name}
author: ${project.author}
version: ${project.version}
main: ${project.mainClass}
api-version: 1.13
description: A 100% customizable crate plugin for your server.
softdepend: [HolographicDisplays,IndividualHolograms,Holograms,Citizens,CMI,PlaceholderAPI,Multiverse-Core,Vault]
commands:
  scrates:
    description: All commands for the specialized crates plugin.
    aliases: [ccrates,crates,specializedcrates,sc,crate]
  keys:
    description: See how many virtual keys you have for your crates.
    aliases: [skeys,cratekey,cratekeys]
  rewards:
    description: Open a rewards menu for a crate